### PR TITLE
Device builder

### PR DESCRIPTION
**Pull request by Kaderimon**
Renamed components, changed some components type to stateless, and added wrapper to chart for responsiveness

### CODE REVIEW

**Review by RostyslavSt — APPROVED** [review]
+

**Review by LanaAvry — APPROVED** [review]
+

**Review by AnastasiiaHamaiunova — APPROVED** [review]

**Review by tatyana-budnyk — COMMENTED** [review]
+

**Review by LanaAvry — APPROVED** [review]
+

**Pull request merged**
